In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras

In [3]:
dataset = tf.data.Dataset.from_tensor_slices((np.arange(10), ['a','b','c','d','e','f','g','h','i','j']))
print(dataset)

<TensorSliceDataset shapes: ((), ()), types: (tf.int64, tf.string)>


In [4]:
for item in dataset:
    print(item)

(<tf.Tensor: id=9, shape=(), dtype=int64, numpy=0>, <tf.Tensor: id=10, shape=(), dtype=string, numpy=b'a'>)
(<tf.Tensor: id=11, shape=(), dtype=int64, numpy=1>, <tf.Tensor: id=12, shape=(), dtype=string, numpy=b'b'>)
(<tf.Tensor: id=13, shape=(), dtype=int64, numpy=2>, <tf.Tensor: id=14, shape=(), dtype=string, numpy=b'c'>)
(<tf.Tensor: id=15, shape=(), dtype=int64, numpy=3>, <tf.Tensor: id=16, shape=(), dtype=string, numpy=b'd'>)
(<tf.Tensor: id=17, shape=(), dtype=int64, numpy=4>, <tf.Tensor: id=18, shape=(), dtype=string, numpy=b'e'>)
(<tf.Tensor: id=19, shape=(), dtype=int64, numpy=5>, <tf.Tensor: id=20, shape=(), dtype=string, numpy=b'f'>)
(<tf.Tensor: id=21, shape=(), dtype=int64, numpy=6>, <tf.Tensor: id=22, shape=(), dtype=string, numpy=b'g'>)
(<tf.Tensor: id=23, shape=(), dtype=int64, numpy=7>, <tf.Tensor: id=24, shape=(), dtype=string, numpy=b'h'>)
(<tf.Tensor: id=25, shape=(), dtype=int64, numpy=8>, <tf.Tensor: id=26, shape=(), dtype=string, numpy=b'i'>)
(<tf.Tensor: id=27, 

In [5]:
# 1. repeat epoch
# 2. get batch
dataset = dataset.repeat(3).batch(7)
for item in dataset:
    print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int64)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int64)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int64)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int64)
tf.Tensor([8 9], shape=(2,), dtype=int64)


In [8]:
# interleave:
# case: file dataset -> 具体数据集

dataset2 = dataset.interleave(
    # map_fn
    # cycle_length 并行处理多少个元素
    # block_length 每次取多少个元素出来
    lambda v: tf.data.Dataset.from_tensor_slices(v),
    cycle_length = 6,
    block_length = 4
)

for item in dataset2:
    print(item)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype

In [10]:
x = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array(['cat', 'dog', 'fox'])
dataset3 = tf.data.Dataset.from_tensor_slices((x, y))
for item_x, item_y in dataset3:
    print(item_x.numpy(), item_y.numpy())

[1 2] b'cat'
[3 4] b'dog'
[5 6] b'fox'


In [12]:
dataset4 = tf.data.Dataset.from_tensor_slices({'feature': x, 'label': y})
for item in dataset4:
    print(item['feature'].numpy(), item['label'].numpy())

[1 2] b'cat'
[3 4] b'dog'
[5 6] b'fox'
