In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras


In [2]:
d = np.arange(0,60).reshape([12, 5])
print(d)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


In [6]:

data = tf.data.Dataset.from_tensor_slices(d)

data = data.shuffle(buffer_size=4)

for i in data.take(6):
    print(i)



tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int64)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
tf.Tensor([25 26 27 28 29], shape=(5,), dtype=int64)
tf.Tensor([15 16 17 18 19], shape=(5,), dtype=int64)
tf.Tensor([20 21 22 23 24], shape=(5,), dtype=int64)
tf.Tensor([35 36 37 38 39], shape=(5,), dtype=int64)


In [8]:
data2 = data.batch(3)
for i in data2.take(6):
    print(i)

tf.Tensor(
[[ 5  6  7  8  9]
 [20 21 22 23 24]
 [ 0  1  2  3  4]], shape=(3, 5), dtype=int64)
tf.Tensor(
[[30 31 32 33 34]
 [35 36 37 38 39]
 [15 16 17 18 19]], shape=(3, 5), dtype=int64)
tf.Tensor(
[[10 11 12 13 14]
 [25 26 27 28 29]
 [55 56 57 58 59]], shape=(3, 5), dtype=int64)
tf.Tensor(
[[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]], shape=(3, 5), dtype=int64)
